ERROR:root:Erro na pagina 1
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 2
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 3
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 4
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 5
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 6
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 7
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 8
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 9
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 10
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 11
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 12
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 13
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 14
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 15
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 16
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 17
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 18
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 19
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 20
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 21
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 22
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 23
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 24
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 25
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 26
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 27
Traceback (most recent call last):
  File "screu.py", line 26, in <module>
    soup = bs4.BeautifulSoup(response.text)
NameError: name 'bs4' is not defined
ERROR:root:Erro na pagina 1
Traceback (most recent call last):
  File "screu.py", line 28, in <module>
    for div in soup.find_all(class_='size1of3'):
TypeError: 'NoneType' object is not callable
ERROR:root:Erro na pagina 2
Traceback (most recent call last):
  File "screu.py", line 28, in <module>
    for div in soup.find_all(class_='size1of3'):
TypeError: 'NoneType' object is not callable
ERROR:root:Erro na pagina 3
Traceback (most recent call last):
  File "screu.py", line 28, in <module>
    for div in soup.find_all(class_='size1of3'):
TypeError: 'NoneType' object is not callable
ERROR:root:Erro na pagina 4
Traceback (most recent call last):
  File "screu.py", line 28, in <module>
    for div in soup.find_all(class_='size1of3'):
TypeError: 'NoneType' object is not callable
ERROR:root:Erro na pagina 5
Traceback (most recent call last):
  File "screu.py", line 28, in <module>
    for div in soup.find_all(class_='size1of3'):
TypeError: 'NoneType' object is not callable
